apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      service: backend-feed
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: giapdbudacity/udagram-api-feed:v1
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "4096Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_HOST
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_DB
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: JWT_SECRET               
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_REGION    
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_PROFILE  
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    service: backend-feed 
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: backend-feed